server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pluglr_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariPool
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: akpeledavidprogress@gmail.com
    password: hmzdtwrpkwjmcvcv
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false


jwt:
  secret-key: lcBCilFEQT0SWEZcCQhGx2UaCZcxPx4bYBfrGM0DVKDJycK2UL4dDJqAkZ8r4IBQxSa3S2wlTVlnVVzvzP5sfzPtLUournmEY2N3ZGVnQ1BtWEF0anZ0aDNLNHJhaHh9IkFVaj0PXA==

iot:
  platform:
    customer:
      service:
        email: artexnetworkservice@gmail.com

file:
  upload-dir: src/main/resources/static/image

web:
    resources:
      static-locations: classpath:/static/

app:
  jwt:
    secret: lcBCilFEQT0SWEZcCQhGx2UaCZcxPx4bYBfrGM0DVKDJycK2UL4dDJqAkZ8r4IBQxSa3S2wlTVlnVVzvzP5sfzPtLUournmEY2N3ZGVnQ1BtWEF0anZ0aDNLNHJhaHh9IkFVaj0PXA==

notification-service:
  base-url: http://localhost:8079

redis:
  host: localhost
  port: 6379

main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: DEBUG
